# This is an AuditLogSearchEnabled Inspector.

# Date: 22-11-2022
# Version: 1.0
# Product Family: Microsoft Exchange
# Purpose: Checks if the AuditLog Search is enabled or not.
# Author: Leonardo van de Weteringh

# Enables error handling if you have the Write-ErrorLog script in the parent directory
$errorHandling = "$((Get-Item $PSScriptRoot).Parent.FullName)\Write-ErrorLog.ps1"

# Sets the Action Preference when an error occurs. Default is Stop
$ErrorActionPreference = "Stop"

# Calls the Error Handling to check if it is existing
. $errorHandling

function Build-AuditLogSearchEnabled($findings)
{
	#Actual Inspector Object that will be returned. All object values are required to be filled in.
	$inspectorobject = New-Object PSObject -Property @{
		ID			    = "M365SATFMEX0007"
		FindingName		= "Unified Audit Log Search is Not Enabled"
		ProductFamily	= "Microsoft Exchange"
		CVS				= "0.0"
		Description		= "Office 365 Unified Audit Log Search is not enabled in the organization. Unified Audit Log Search allows for the centralized ingestion and searching of audit logs generated by Office 365 and can be a vital source of data for the investigation and detection of security incidents. It is highly recommended to enable unified audit log searching."
		Remediation		= "Use the PowerShell Script to Mitigate this issue." 
        PowerShellScript= 'Enable-OrganizationCustomization; Set-AdminAuditLogConfig -UnifiedAuditLogIngestionEnabled $true; Set-AdminAuditLog -UnifiedAuditLogInvestigationEnabled $true'
		DefaultValue	= "False"
		ExpectedValue	= "True"
		ReturnedValue	= $findings
		Impact			= "Informational"
		RiskRating 		= "Informational"
		References		= @(@{'Name'= 'Enabling the Unified Audit Log on all delegated Office 365 tenants via PowerShell';'URL'= 'https://gcits.com/knowledge-base/enabling-unified-audit-log-delegated-office-365-tenants-via-powershell/'})
	}
    return $inspectorobject
}

function Inspect-AuditLogSearchEnabled {
Try {
	$module = (get-command Get-AdminAuditLogConfig).Source



	If (-NOT (Get-AdminAuditLogConfig).UnifiedAuditLogIngestionEnabled) {
		$finding = (Get-AdminAuditLogConfig).UnifiedAuditLogIngestionEnabled
        $finalobject = Build-AuditLogSearchEnabled($finding)
        return $finalobject
	}
	
	return $null

}
Catch {
Write-Warning "Error message: $_"
$message = $_.ToString()
$exception = $_.Exception
$strace = $_.ScriptStackTrace
$failingline = $_.InvocationInfo.Line
$positionmsg = $_.InvocationInfo.PositionMessage
$pscommandpath = $_.InvocationInfo.PSCommandPath
$failinglinenumber = $_.InvocationInfo.ScriptLineNumber
$scriptname = $_.InvocationInfo.ScriptName
Write-Verbose "Write to log"
Write-ErrorLog -message $message -exception $exception -scriptname $scriptname
Write-Verbose "Errors written to log"
}

}

return Inspect-AuditLogSearchEnabled


